development:
  domain: http://localhost:3001
  mailchimp:
    api_key: 9b98484528f3f824d34df46c8672a168-us5
    list_id: da461e7340
  robokassa:
    login: 'sharipov'
    secret1: 'iddqdkfa83'   # for notification method
    secret2: 'robox1212'
  facebook:
    AppID: 521885384495458
    admins: 100001720278298
  vkontakte:
    AppID: 3104899
  2gis_map_id: 'd263f13b06daad57b9f5061d74b42311'

staging:
  domain: http://office.7bits.it:21780
  mailchimp:
    api_key: 9b98484528f3f824d34df46c8672a168-us5
    list_id: da461e7340
  robokassa:
    login: 'EugeneTarasenko'
    secret1: 'dkhtdkjhpbkcp,2012'   # for notification method
    secret2: 'bdjyygrygbvvhlg2012'
  facebook:
    AppID: 521885384495458
    admins: 100001720278298
  vkontakte:
    AppID: 3104899
  2gis_map_id: '1a231b1f06c4f241c7d630691756a3b7'

production:
  domain: http://happydev.ru
  mailchimp:
    api_key: 2b25ec06f724c27a6b57a795fc5d1f37-us5
    list_id: 30503cd22e
    list_id_7bits_friends: 9c2718348c
  robokassa:
    login: 'AnnieOmsk'
    secret1: 'dkhtdkjhpbkcp,2012'   # for notification method
    secret2: 'bdjyygrygbvvhlg2012'
  facebook:
    AppID: 494138303932424
    admins: 100001720278298
  vkontakte:
    AppID: 3104781
  2gis_map_id: '398515700752a255c6f4ba03702e376e'

# tmp:
  # robokassa:
  #   login: 'sharipov'
  #   secret1: 'iddqdkfa83'   # for notification method
  #   secret2: 'robox1212'
